version: '2'
services:
  agenda-rest:
    container_name: agenda-rest
    build: .
    environment:
      - "DB_NAME=agenda"
      - "DB_HOST=mongo"
      - "DB_PORT=27017"
    ports:
      - "4040:4040"
    depends_on:
      - mongo
    links:
      - mongo

  agendasha:
    container_name: agendash
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - "DB_NAME=agenda"
      - "DB_HOST=mongo"
    ports:
      - "3022:3022"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    expose:
      - "27017"
